window.REACT_APP_PublicGatewayApiBaseURL= 'https://api-portal.invoicing.eta.gov.eg/'
window.REACT_APP_stsAuthority= 'https://id.eta.gov.eg/'
window.REACT_APP_clientId= '9A029E3B-7403-4B25-8850-AB67E1FD92AB'
window.REACT_APP_clientScope= 'openid profile publicportals.bff.api'
window.REACT_APP_clientRoot= 'https://invoicing.eta.gov.eg/'
window.REACT_APP_ReleaseId = '19839'
window.REACT_APP_ReleaseName = 'R-0218.2.1'
window.REACT_APP_RegistrationPortalURL= 'https://profile.eta.gov.eg/'
window.REACT_APP_GuidancePortalURL= 'https://www.eta.gov.eg/ar/content/e-invoice-services'
window.REACT_APP_InvoiceLineGS1MeasureCodes= 'GS1 Measure Codes'
window.REACT_APP_InvoiceLineGS1Code= 'GS1'
window.REACT_APP_InvoiceLineTaxTypes= 'Tax Type'
window.REACT_APP_FrequentlyUsedCodesToken= 'FrequentlyUsedCodesToken'
window.REACT_APP_InvoiceItemCodeMiniLen= '4'
window.REACT_APP_InvoiceItemCodeMaxLen= '100'
window.REACT_APP_AllowFeatureFlagControl= ''
window.REACT_APP_DraftAndTemplateEnabled= 'true'
window.REACT_APP_TaxesAttribute= 'AmountType'
window.REACT_APP_Amount= 'amount'
window.REACT_APP_FreeSearchTextMiniLen= '5'
window.REACT_APP_MaxBatchNo= '10'
window.REACT_APP_SaveDraftDocumentTimerMins=2;
window.REACT_APP_CashingLifeTimeMinute=1440;
window.REACT_APP_SearchReceiptWaitingTimeMins=120;
window.REACT_APP_InitialLineItemsCount=100;
window.REACT_APP_ReciptBulkUploadFileSizeInMB = 25;
window.REACT_APP_MaxRecipt = 500;
window.REACT_APP_Maxsubmission = 100;
window.REACT_APP_MaxJson = 2560;
window.REACT_APP_ReceiptBatchSchemaURL = 'https://sdk.invoicing.eta.gov.eg/';
window.REACT_APP_Fabric_Icons_CDN = 'https://static2.sharepointonline.com/files/fabric/assets/icons/'
